version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=pocdb
    ports:
      - '5432:5432'

  poc_app:
    container_name: poc_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8811'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/pocdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresql
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db